services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=App
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./AppWebApi
      dockerfile: dockerfile
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DOTNET_hostBuilder__reloadConfigOnChange=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Defaultconnection=Host=db;Port=5432;Database=App;Username=postgres;Password=YourStrong@Passw0rd;

  frontend:
    build:
      context: ./App
      dockerfile: dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: