apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  namespace: myapp
spec:
  restartPolicy: Never
  containers:
    - name: psql
      image: postgres:16
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-db-credentials
              key: password
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: myapp-db-credentials
              key: username
      command: ["sh", "-c"]
      args:
        - |
          H=myapp-prod-postgres.c74wqq0ywt57.ap-southeast-1.rds.amazonaws.com
          echo "== psql =="
          psql "host=$H port=5432 dbname=App sslmode=verify-full sslrootcert=/etc/ssl/certs/rds/rds-ca.pem" -c "select 1"
      volumeMounts:
        - name: rds-ca
          mountPath: /etc/ssl/certs/rds
  volumes:
    - name: rds-ca
      configMap:
        name: aws-rds-ca