events {}

http {
    upstream backend_servers {
        server tf-backend-1:8080;
        server tf-backend-2:8080;
        server tf-backend-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}