# ---- Build Stage ----
FROM node:22-alpine AS build
WORKDIR /app

ARG BUILD_CONFIG=production

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration=$BUILD_CONFIG

# ---- Runtime Stage ----
FROM nginx:alpine AS runtime
COPY --from=build /app/dist/App/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80